// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.java8annotation.type;

import com.apollographql.apollo.api.InputType;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.Utils;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import org.jetbrains.annotations.NotNull;

public final class Login implements InputType {
  private final @NotNull String email;

  private transient volatile int $hashCode;

  private transient volatile boolean $hashCodeMemoized;

  Login(@NotNull String email) {
    this.email = email;
  }

  public @NotNull String email() {
    return this.email;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public InputFieldMarshaller marshaller() {
    return new InputFieldMarshaller() {
      @Override
      public void marshal(InputFieldWriter writer) throws IOException {
        writer.writeString("email", email);
      }
    };
  }

  @Override
  public int hashCode() {
    if (!$hashCodeMemoized) {
      int h = 1;
      h *= 1000003;
      h ^= email.hashCode();
      $hashCode = h;
      $hashCodeMemoized = true;
    }
    return $hashCode;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Login) {
      Login that = (Login) o;
      return this.email.equals(that.email);
    }
    return false;
  }

  public static final class Builder {
    private @NotNull String email;

    Builder() {
    }

    public Builder email(@NotNull String email) {
      this.email = email;
      return this;
    }

    public Login build() {
      Utils.checkNotNull(email, "email == null");
      return new Login(email);
    }
  }
}
